# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://github.com/actions/runner-images/tree/main/images/macos
# https://github.com/actions/runner-images/tree/main/images/ubuntu
name: CI

on:
  push:
    branches:
      - main
      - ci/**
  pull_request:

jobs:
  swiftformat:
    name: SwiftFormat lint
    runs-on: ubuntu-latest
    container: swift:6.2
    steps:
      - uses: actions/checkout@v4
      - name: Cache SPM build
        uses: actions/cache@v4
        with:
          path: .build
          key: swiftformat-${{ hashFiles('Package.resolved') }}
          restore-keys: swiftformat-
      - name: Lint
        run: swift package plugin --allow-writing-to-package-directory swiftformat --lint

  xcode-build:
    name: Xcode build ${{ matrix.platform }}
    runs-on: macos-26
    strategy:
      matrix:
        xcode: ["26.4"]
        platform: ["iOS", "macOS", "watchOS", "tvOS", "visionOS"]
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Build ${{ matrix.platform }} package
      run: make xcode-build OS=${{ matrix.platform}}

  ubuntu:
    name: Ubuntu test
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    strategy:
      matrix:
        swift:
          - '6.2'
    steps:
      - uses: actions/checkout@v4

      - name: Install make
        run: apt-get update && apt-get install -y make

      - name: Build Ubuntu package
        run: TEST_CLOCK=1 make swift-test

  required:
    name: Required
    needs:
      - swiftformat
      - xcode-build
      - ubuntu
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs
        env:
          NEEDS: ${{ toJson(needs) }}
        run: |
          ! echo "$NEEDS" | jq -e 'to_entries[] | { job: .key, result: .value.result } | select((.result == "success" or .result == "skipped") | not)'
